home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('',views.home,name="home")
]

play/urls.py
from django.urls import path
from . import views

app_name = "play"

urlpatterns = [
	path('',views.default_redirect_computer,name="default_play"),
    path('computer/',views.play_with_computer,name="computer"),
    path('human/',views.play_with_human,name="human"),
    path('computer/<int:points>/',views.start_game,name="start-game"),
    path('who-win/',views.who_win,name="who-win"),
    path('waiting-room/',views.waiting_room,name="waiting-room"),
    path('wait-for-opponent/',views.waiting_for_opponent,name="wait-for-opponent"),
    path("human/game-start/",views.human_play,name="human-game-start"),
    path("human-compare/",views.human_compare,name="human-compare"),
    path("reset-choice/",views.reset_choice,name="reset-choice"),
    path("go-home/",views.go_home,name="go-home")
]

rps/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("home.urls")),
    path('play/',include("play.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect

def home(request):
	return render(request,"home/home.html")

home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

  <title>Rock Paper Scissor</title>

  <meta link-colorarset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

  <script src='https://kit.fontawesome.com/a076d05399.js'></script>

  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Ubuntu:wght@500&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Big+Shoulders+Stencil+Text:wght@300&family=Bungee+Outline&family=Geostar+Fill&family=Londrina+Shadow&family=Londrina+Sketch&family=Michroma&family=Orbitron&display=swap" rel="stylesheet">


  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}?{% now 'U' %}">

  {% block style %} {% endblock style %}

</head>

<body>

  <section id="header" class="mt-3">
    <div class="container d-flex justify-content-center p-2">
      <img src="{% static 'media/rps-logo.jpg' %}" class="logo mr-2"/>
      <h4 class="mt-2 title">Rock Paper Scissor</h4>
    </div>
  </section>


	{% block content %}	{% endblock content %}

  <!-- Footer -->
  <footer id="footer" class="text-center m-5">
    <small class="text-light" style="font-family:calibri">© Copyright 2020 RPS </small>
  </footer>

  {% block script %} {% endblock script %}

</body>
</html>


home/templates/home/home.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
	
	<section id="body" class="mt-5">
		<div class="container p-2 mt-4 rounded shadow" style="background:#153e90">
			<div class="row">
				<div class="col-4 text-center">
					<img src="{% static 'media/rock.png' %}" class="rps-img"/>
				</div>
				<div class="col-4 text-center">
					<img src="{% static 'media/paper.png' %}" class="rps-img"/>
				</div>
				<div class="col-4 text-center">
					<img src="{% static 'media/scissor.png' %}" class="rps-img"/>
				</div>
			</div>
		</div>
		<div class="container p-2 mt-4">
			<div class="row">
				<div class="col-lg-6 col-md-6 text-center mt-2">
					<a href="{% url 'play:computer' %}"><button type="button" class="rps-btn vs-btn computer rounded">Vs. Computer</button></a>
				</div>
				<div class="col-lg-6 col-md-6 text-center mt-2">
					<a href="{% url 'play:human' %}"><button type="button" class="rps-btn vs-btn human rounded">Vs. Human</button></a>
				</div>
			</div>
		</div>
	</section>
	

{% endblock content %}