home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('',views.home,name="home")
]

play/urls.py
from django.urls import path
from . import views

app_name = "play"

urlpatterns = [
	path('',views.default_redirect_computer,name="default_play"),
    path('computer/',views.play_with_computer,name="computer"),
    path('human/',views.play_with_human,name="human"),
    path('computer/<int:points>/',views.start_game,name="start-game"),
    path('who-win/',views.who_win,name="who-win"),
    path('waiting-room/',views.waiting_room,name="waiting-room"),
    path('wait-for-opponent/',views.waiting_for_opponent,name="wait-for-opponent"),
    path("human/game-start/",views.human_play,name="human-game-start"),
    path("human-compare/",views.human_compare,name="human-compare"),
    path("reset-choice/",views.reset_choice,name="reset-choice"),
    path("go-home/",views.go_home,name="go-home")
]

rps/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("home.urls")),
    path('play/',include("play.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


play/models.py
from django.db import models


class Room(models.Model):
	u_id = models.CharField(max_length=60,unique=True)
	def __str__(self):
		return self.u_id
	class Meta:
		verbose_name_plural = "Room"


class player(models.Model):
	join_id = models.ForeignKey(Room,on_delete=models.CASCADE)
	player_name = models.CharField(max_length=15)
	points_decided = models.IntegerField(default=10)
	creater = models.BooleanField(default=True)
	rps_choice = models.CharField(max_length=8,blank=True,null=True)
	def __str__(self):
		return self.player_name + " of Room " + self.join_id.u_id
	class Meta:
		verbose_name_plural = "Player"

play/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from django.urls import reverse
from .passwordGenerator import passwordGenerator as PG
from .models import Room
import random
import time
import math

# COMPUTER
def default_redirect_computer(request):
	return HttpResponseRedirect(reverse("play:computer"))

def redirect_computer(request,unknown_player):
	return HttpResponseRedirect(reverse("play:computer"))

def play_with_computer(request):
	return render(request,"play/computer-index.html",{})

def start_game(request,points):
	context = {}
	if points not in [3,5,10]:
		points = 5 #default points
		context['message'] = "Points entered are not valid. Default is a 5 pointer game. You can go back and change the points."
	context['instruction'] = "Press Key <u><b>&quot;R&quot;</b> for Rock</u>, <u><b>&quot;P&quot;</b> for Paper</u>, <u><b>&quot;S&quot;</b> for Scissor</u>."
	context['points'] = points
	return render(request,"play/computer-start.html",context)

def who_win(request):
	rps_choice = ['rock','paper','scissor']
	if request.GET:
		data = {}
		userChoice = request.GET.get('keyPressed')
		computerChoice = random.randint(0,2)
		userChoiceIndex = rps_choice.index(userChoice)
		if userChoiceIndex == 0 and computerChoice == 1:
			data['userWin'] = False
		elif userChoiceIndex == 0 and computerChoice == 2:
			data['userWin'] = True
		elif computerChoice == 0 and userChoiceIndex == 2:
			data['userWin'] = False
		elif userChoiceIndex > computerChoice:
			data['userWin'] = True
		elif userChoiceIndex < computerChoice:
			data['userWin'] = False
		elif computerChoice == userChoiceIndex:
			data['userWin'] = "Tie"
		data['computerChoice'] = computerChoice

		return JsonResponse(data)


# HUMAN
def play_with_human(request):
	context = {}
	unique_key = random.randint(1111,9999) # 4 digit random number
	password = PG.generateID(unique_key=unique_key)
	context['ID'] = password
	if request.POST:
		room_id = request.POST.get("unique-id")
		game_points = request.POST.get("points")
		player_name = request.POST.get("name")

		try:
			roomIdExists = Room.objects.filter(u_id=room_id)
		except:
			pass
		else:
			request.session['roomID'] = room_id
			request.session['playerName'] = player_name
			if len(roomIdExists) > 1:
				#More than 1 room with same ID cannot be created 
				del request.session['roomID']
				del request.session['playerName']
				context['message'] = "This Rooom ID already Exists. Get some new ID"
			elif len(roomIdExists) == 1:
				#Room already exists, Just player is need to be added
				'''
				NOTE: This room is already created 
					  Room strength is 2, One player is already added while creating the room
					  Only one player can be added now
				'''
				getRoom = Room.objects.get(u_id=room_id)
				getPlayersOfThisRoom = getRoom.player_set.all()
				if len(getPlayersOfThisRoom) == 1:
					# second player can be added
					setSecondPlayer = getRoom.player_set.create(player_name=player_name,points_decided=game_points,creater=False,rps_choice="")
					return HttpResponseRedirect(reverse("play:waiting-room"))
				else:
					#Room is full, New player cannot be added
					del request.session['roomID']
					del request.session['playerName']
					context['message'] = "This Room is already filled up."

			else:
				#Room doesnot exists, First create Room then add player  
				createRoom = Room.objects.create(u_id=room_id)
				getCreatedRoom = Room.objects.get(u_id=room_id)
				setFirstPlayer = getCreatedRoom.player_set.create(player_name=player_name,points_decided=game_points,creater=True,rps_choice="")
				#NOTE: This player created the room so he is the first player
				return HttpResponseRedirect(reverse("play:waiting-room"))
	return render(request,"play/human-index.html",context)


def waiting_room(request):
	return render(request,'play/human-start.html')

def waiting_for_opponent(request):
	try:
		room_id = request.session['roomID']
		room = Room.objects.get(u_id=room_id)
	except:
		return HttpResponseRedirect(reverse("play:human"))
	else:
		jsonData = {'playersJoined':False}
		players = room.player_set.all()
		if len(players) == 2:
			jsonData['playersJoined'] = True
			return JsonResponse(jsonData)
		return JsonResponse(jsonData)


def human_play(request):
	try:
		room_id = request.session['roomID']
		player_name = request.session['playerName']
		room = Room.objects.get(u_id=room_id)
	except:
		return HttpResponseRedirect(reverse("play:human"))
	else:
		context = {}
		context['instruction'] = "<p>Press Key <u><b>&quot;R&quot;</b> for Rock</u>, <u><b>&quot;P&quot;</b> for Paper</u>, <u><b>&quot;S&quot;</b> for Scissor</u></p><br><p><b>After choosing your choice wait for the next player to select their choice.</b></p>"

		players = room.player_set.all() #Query Set for Both the players of the room
		player_1 = room.player_set.first() #Query set for player 1 as per the database, he is the creater
		player_2 = room.player_set.last() #Query set for player 2 as per the database
		p1_points = player_1.points_decided
		p2_points = player_2.points_decided
		game_points = math.floor((p1_points+p2_points)/2)

		playerA = player_name # (You) this is the session Player
		for player in players:
			if player.player_name != playerA:
				playerB = player.player_name #opponent
		
		context.update({"playerA":playerA,"playerB":playerB,"gamePoints":game_points})	
		return render(request,"play/human-play.html",context)

def human_compare(request):
	try:
		room_id = request.session['roomID']
		player_name = request.session['playerName']
	except:
		pass
	else:
		rps_choice = ['rock','paper','scissor']
		playerA = player_name # (you) player
		data = {}
		room = Room.objects.get(u_id=room_id)
		players = room.player_set.all()
		for player in players:
			if player.player_name != playerA:
				playerB = player.player_name #opponent
		playerA_query = room.player_set.get(player_name=playerA)
		playerB_query = room.player_set.get(player_name=playerB)

		userChoice = request.GET.get("userChose")
		playerA_query.rps_choice = userChoice
		playerA_query.save()

		if playerB_query.rps_choice == None or playerB_query.rps_choice == "":
			data['opponentSelected'] = False
			return JsonResponse(data)
		else:
			pA_rps = playerA_query.rps_choice
			pB_rps = playerB_query.rps_choice
			pA_rpsIndex = rps_choice.index(pA_rps)
			pB_rpsIndex = rps_choice.index(pB_rps)
			data['playerB_Choice'] = pB_rpsIndex
			if pA_rpsIndex == 0 and pB_rpsIndex == 1: #rock and paper
				data['pA_Win'] = False
			elif pA_rpsIndex == 0 and pB_rpsIndex == 2: #rock and scissor
				data['pA_Win'] = True
			elif pB_rpsIndex == 0 and pA_rpsIndex == 2: #rock and scissor
				data['pA_Win'] = False
			elif pA_rpsIndex > pB_rpsIndex:
				data['pA_Win'] = True
			elif pA_rpsIndex < pB_rpsIndex:
				data['pA_Win'] = False
			elif pA_rpsIndex == pB_rpsIndex:
				data['pA_Win'] = "tie"
			time.sleep(1)
			data['opponentSelected'] = True
			return JsonResponse(data)


def reset_choice(request):
	room_id = request.session['roomID']
	playerName = request.session['playerName']
	playerA = playerName
	room = Room.objects.get(u_id=room_id)
	players = room.player_set.all()
	for player in players:
		if player.player_name != playerA:
			playerB = player.player_name 
	playerA_query = room.player_set.get(player_name=playerA)
	playerB_query = room.player_set.get(player_name=playerB)
	playerA_query.rps_choice = ""
	playerA_query.save()
	playerB_query.rps_choice = ""
	playerB_query.save()
	data = {'successfullReset':True}
	return JsonResponse(data)

def go_home(request):
	try:
		room_id = request.session['roomID']
		room = Room.objects.get(u_id=room_id)
	except:
		return HttpResponseRedirect(reverse("home:home"))
	else:
		room.delete()
		return HttpResponseRedirect(reverse("home:home"))

play/templates/play/computer-index.html
{% extends 'home/base.html' %}

{% load static %}

{% block style %}

{% endblock style %}

{% block content %}

	<section id="body" class="mt-5">
		<div class="container p-2 mt-4 rounded shadow" style="background:#153e90">
			<div class="row">
				<div class="col-4 text-center">
					<img src="{% static 'media/rock.png' %}" class="rps-img"/>
				</div>
				<div class="col-4 text-center">
					<img src="{% static 'media/paper.png' %}" class="rps-img"/>
				</div>
				<div class="col-4 text-center">
					<img src="{% static 'media/scissor.png' %}" class="rps-img"/>
				</div>
			</div>
		</div>
		<div class="container mt-5">
			<div class="d-flex flex-wrap justify-content-around">
				<a href="{% url 'play:start-game' 3 %}"><button type="button" class="rps-btn points-btn computer pl-4 pr-4 m-2 rounded">3 Pointer</button></a>
				<a href="{% url 'play:start-game' 5 %}"><button type="button" class="rps-btn points-btn computer pl-4 pr-4 m-2 rounded">5 Pointer</button></a>
				<a href="{% url 'play:start-game' 10 %}"><button type="button" class="rps-btn points-btn computer pl-4 pr-4 m-2 rounded">10 Pointer</button></a>
			</div>
		</div>
	</section>

{% endblock content %}


play/templates/play/computer-start.html
{% extends 'home/base.html' %}
{% load static %}


{% block content %}


	<section id="body" class="mt-3">

		<div class="container text-center text-light mb-1">
			<h5 class="game-message" data-id="{{ points }}">You Vs. Computer</h5>
		</div>

		<div class="container">
			<table class="table table-bordered table-dark text-center">
			  <thead>
			    <tr>
			      <th scope="col">You</th>
			      <th scope="col">Computer</th>
			    </tr>
			  </thead>
			  
			  <tbody>
			    <tr>
			      <td class="user_td"><img src="{% static 'media/rps-logo.jpg' %}" class="rps-icon user-icon"/></td>
			      <td class="computer_td"><img src="{% static 'media/rps-logo.jpg' %}" class="rps-icon computer-icon"/></td>
			    </tr>

			    <tr class="bg-warning">
			      <td class="text-dark font-weight-bolder">Score : <span class="human-score">0</span></td>
			      <td class="text-dark font-weight-bolder">Score : <span class="computer-score">0</span></td>
			    </tr>
			  </tbody>

			</table>
		</div>
	</section>


	<div class="modal modal-fade" id="result-message-modal">
		<div class="modal-dialog modal-dialog-centered">
			<div class="modal-content">
				<div class="modal-header">
					<h3 class="result-tag"></h3>
					<button type="button" class="close" onfocus="this.style.outline='none'" data-dismiss="modal"><span>&times;</span></button>
				</div>
				<div class="modal-body">
					<p class="lead result-message"></p>
					<div class="d-flex justify-content-center">
						<a href="#" class="mr-2" onclick='location.reload()'>Play Again</a>
						<a href="{% url 'home:home' %}" class="ml-2">Go Home</a>
					</div>
				</div>
			</div>
		</div>
	</div> 


{% if instruction %}
	
	<div class="modal modal-fade" id="message-modal">
		<div class="modal-dialog modal-dialog-centered">
			<div class="modal-content">
				<div class="modal-header">
					<h3>Instructions</h3>
					<button type="button" class="close" onfocus="this.style.outline='none'" data-dismiss="modal"><span>&times;</span></button>
				</div>
				<div class="modal-body">
					<p class="lead">{{ instruction|safe }}</p>
				</div>
			</div>
		</div>
	</div> 

	<script>$("#message-modal").modal('show');</script>

{% endif %}

{% endblock content %}

{% block script %}
	<script type="text/javascript" src="{% static 'js/computer-game.js' %}"></script>
{% endblock script %}

play/templates/play/human-index.html
{% extends 'home/base.html' %}

{% load static %}

{% block style %}

{% endblock style %}

{% block content %}

	<section id="body" class="mt-5">
		<div class="container p-2 text-center mt-4">
			<h5 class="share-text" style="color:#fffaa4">Share this ID with your freind</h5>
			<div class="input-group w-responsive mx-auto">
			    <input type="text" class="form-control text-center" id="unique-id" readonly value="{{ ID }}">
			    <div class="input-group-btn">
			      <button class="btn btn-info copy-btn" type="submit" title="Copy" data-placement="top" data-toggle="tooltip">
			        <i class="fas fa-clipboard"></i>
			      </button>
			    </div>
			</div>
		</div>
		<div class="container mt-5">
			<h4 class="text-center font-michroma" style="color:#54e346">Login to Play the Game</h4>
			<div class="row mt-5">
				<div class="col-lg-5 p-3">
					<h5 class="text-light">Instruction</h5>
					<ul style="color:#fffaa4">
						<li>Share the unique code above with your friend to play.</li>				
						<li>Either Player 1 share his key for both to Login or Player 2 share his Key for Login</li>
						<li>In this Login, Both the players should enter the same key in order to get register for the game</li>
						<li>Both the Player should select the Same points or it will be the mean of two different selected points.</li>
						<li>Don't Go for same name.</li>
					</ul>
				</div>
				<div class="col-lg-7 text-center p-3 rounded shadow" style="border:2px solid #fffaa4">
					<form action="{% url 'play:human' %}" method="post">

						{% csrf_token %}
					  
					  <div class="form-group mt-2">
					    <input type="text" class="form-control" name="unique-id" id="unique-id-login" placeholder="Enter your Unique Key" autocomplete="false" required spellcheck="false">
					  </div>

					  <div class="form-group mt-3">
						  <div class="radio row">
						  	<div class="col-lg-4">	
						  		<button type="button" class="rps-btn points-btn human pl-4 pr-4 mt-2 rounded w-100">10 Pointer<input type="radio" name="points" required value="10"></button>
						  	</div>
						  	<div class="col-lg-4">
						  		<button type="button" class="rps-btn points-btn human pl-4 pr-4 mt-2 rounded w-100">15 Pointer<input type="radio" name="points" required value="15"></button>
						  	</div>
						  	<div class="col-lg-4">
						  		<button type="button" class="rps-btn points-btn human pl-4 pr-4 mt-2 rounded w-100">20 Pointer<input type="radio" name="points" required value="20"></button>
						  	</div>					    
						  </div>
						</div>

						<div class="form-group mt-2">
							<div class="row">
								<div class="col-lg-6 col-md-6">
									<input type="text" class='form-control w-100 mb-1' name="name" id="login-name" placeholder="Enter You Name" autocomplete="false" required spellcheck="false">
								</div>
								<div class="col-lg-6 col-md-6">
									<button type="submit" class="btn btn-success w-100 font-michroma play-btn mb-1">Play</button>
								</div>
							</div>	
					  	</div>
					  
					</form>
				</div>
			</div>
		</div>
	</section>

	{% if message %}
    <!-- Popop Model for Warning or any Message -->
    <div class="modal modal-fade" id="message-modal">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-body">
            <div class="d-flex justify-content-between">
              <h5 style="font-family:calibri">{{ message }}</h5>
              <button type="button" class="close" onfocus="this.style.outline='none'" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script>$("#message-modal").modal('show');</script>
	<script>$(function() { $('[data-toggle="tooltip"]').tooltip(); })</script>
  {% endif %}

{% endblock content %}

{% block script %}
	<script type="text/javascript" src="{% static 'js/clipboard.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/point-select.js' %}"></script>
{% endblock script %}

play/templates/play/human-play.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
	<section id="body" class="mt-3">

		<div class="container text-center text-light mb-1">
			<h5 class="game-message" data-points="{{ gamePoints }}">{{ playerA }} <span style="color:#fffaa4"><b><i>Vs.</i></b></span> {{ playerB }} [<span style="color:#54e346">{{ gamePoints }} points</span>]</h5>
		</div>

		<div class="container">
			<table class="table table-bordered table-dark text-center">
			  <thead>
			    <tr>
			      <th scope="col">You</th>
			      <th scope="col">{{ playerB }}</th>
			    </tr>
			  </thead>
			  
			  <tbody>
			    <tr>
			      <td class="pA_td"><img src="https://i.pinimg.com/originals/65/ba/48/65ba488626025cff82f091336fbf94bb.gif" class="rps-icon pA-icon"/></td>
			      <td class="pB_td"><img src="https://i.pinimg.com/originals/65/ba/48/65ba488626025cff82f091336fbf94bb.gif" class="rps-icon pB-icon"/></td>
			    </tr>

			    <tr class="bg-warning">
			      <td class="text-dark font-weight-bolder">Score : <span class="pA-score">0</span></td>
			      <td class="text-dark font-weight-bolder">Score : <span class="pB-score">0</span></td>
			    </tr>
			  </tbody>

			</table>
		</div>
	</section>

	<div class="modal modal-fade" id="result-message-modal">
		<div class="modal-dialog modal-dialog-centered">
			<div class="modal-content">
				<div class="modal-header">
					<h3 class="result-tag"></h3>
					<button type="button" class="close" onfocus="this.style.outline='none'" data-dismiss="modal"><span>&times;</span></button>
				</div>
				<div class="modal-body">
					<p class="lead result-message"></p>
					<div class="d-flex justify-content-center">
						<a href="#" class="mr-2" onclick='location.reload()'>Play Again</a>
						<a href="{% url 'play:go-home' %}" class="ml-2">Go Home</a>
					</div>
				</div>
			</div>
		</div>
	</div> 


	{% if message or instruction %}
    <!-- Popop Model for Warning or any Message -->
    <div class="modal modal-fade" id="message-modal">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-body">
            <div class="d-flex justify-content-between">
              <h5 style="font-family:calibri">{% if message %}{{ message }}{% else %}{{ instruction|safe }}{% endif %}</h5>
              <button type="button" class="close" onfocus="this.style.outline='none'" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script>$("#message-modal").modal('show');</script>

  {% endif %}

{% endblock content %}

{% block script %}
	<script type="text/javascript" src="{% static 'js/human-game.js' %}"></script>
{% endblock script %}


play/templates/play/human-start.html
{% extends 'home/base.html' %}

{% block content %}
	<section id="body">
		<div class="container mt-5">
			<h1 class="text-center waiting-text">Waiting for your partner to join</h1>
		</div>
	</section>

	<script>
		$(function(){
			var rep = setInterval(waitForOpponent,2000);
			
			function waitForOpponent() {
				$.ajax({
					type:'GET',
					url:"{% url 'play:wait-for-opponent' %}",
					success:function(json) {
						if(json.playersJoined) {
							clearInterval(rep);
							return location.replace("{% url 'play:human-game-start' %}")
						}
					}
				});
			}
		});
	</script>


{% endblock content %}